### ISSUE TITLE
Website is down?

### ISSUE THREAD

**Issue by sbrl** [ubiety/xmpp#10]
The link to [ubiety.ca](http://ubeity.ca/) seems to be dead.

**Comment by damccull** [comment]
This project still going?

**Comment by sbrl** [comment]
@damccull No idea.

**Comment by fbacker** [comment]
Also wondering if project is still Live? 

Anyone figured out how to connect roster or send/receive messages?

**Comment by sbrl** [comment]
@coder2000 Hello? Is this project still alive? If so, how do you use it?

**Comment by coder2000** [comment]
This project is still alive. As for rosters that isn't implemented yet but the infrastructure to send and receive raw xml messages is there so you can work that out.

**Comment by sbrl** [comment]
@coder2000 Thanks! I will have to take a look into how it works.

Perhaps some basic documentation would help people to get started with greater ease.

**Comment by coder2000** [comment]
There are comments on a lot of the code I just haven't parsed it to create a documentation page. I should mention that to compile the master branch at this time requires the latest version of the .
NET framework.

**Comment by sbrl** [comment]
Right. By the latest version do you mean Visual Studio 2015 + .NET v4.6, 
or VS2013 + .NET v4.5?

**Comment by coder2000** [comment]
.NET 4.6

**Comment by sbrl** [comment]
Ok, thanks!
