### ISSUE TITLE
Can't add it to WP8.1 project

### ISSUE THREAD

**Issue by dutsky** [ubiety/xmpp#13]
Hello! I'm trying to use your lib in WP8.1 project, but can't install it. When I'm trying to add it via NuGet Package Manager I'm getting error: "Could not install package 'ExceptionAnalyzer 1.0.5'. You are trying to install this package into a project that targets 'WindowsPhoneApp,Version=v8.1', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author."

Is it possible to resolve somehow? Thanks

**Comment by ardonjr** [comment]
Hi, it's the same here. Just tried to install via Nuget on a Windows Phone Universall environment. (WP 8.1 and higher)

**Comment by coder2000** [comment]
This package currently does not support WP8.1 or UWP environments. I am currently working on a pcl version of the library but it is requiring me to also create pcl versions for some of the requirements. I will post an update when a pcl version is available.

**Comment by ardonjr** [comment]
Thanks, I can't wait for the PCL lib to become available!

**Comment by othreecodes** [comment]
Any Update on this?

**Comment by othreecodes** [comment]
@coder2000  Whats the Update with the pcl version

**Comment by coder2000** [comment]
You can use the fork by @PaulFruend for any WP8.1 projects. I am working on a .NET Core version and it should be available soon.
