### ISSUE TITLE
Directories differing only in case

### ISSUE THREAD

**Issue by benh57** [ubiety/xmpp#14]
I'm getting build failures and i noticed The git repo has: 

xmpp\ubiety\Core 
xmpp\ubiety\core 

xmpp\ubiety\Infrastructure
xmpp\ubiety\infrastructure

xmpp\ubiety\Common
xmpp\ubiety\common

Depending on your git client on windows, these directories may or may not work. For me, they get merged together. Are they intended to be the same dirs?

**Comment by coder2000** [comment]
They are. For some reason VS didn't do the rename properly. I am going to do a reorg of the project soon that will include a new repo and vs project.

**Comment by benh57** [comment]
Sounds good. I actually noticed that some of the forks (monksoftware, paulfreund) have more complete implementations of the Jabber protocol's tags which the base ubiety is missing. However, they seem to be targeting Win8.1 but i want to build for older clients.

**Comment by coder2000** [comment]
They do. I am working alone in my spare time so progress is slow. If you want to help add those tags and features feel free. I am also looking into making this library pcl compliant which might make those other forks obsolete.

**Comment by coder2000** [comment]
Folders have been fixed.
