### ISSUE TITLE
Readme outdated?

### ISSUE THREAD

**Issue by falsechicken** [ubiety/xmpp#19]
Hello. I am trying to write a component using Ubiety. But it appears the the example in the readme is outdated?

```
ubiety.Settings.ID = new JID("test@ubiety.ca");

Error CS0176: Static member `Ubiety.Xmpp.Settings' cannot be accessed with an instance reference, qualify it with a type name instead (CS0176)
```

Using MonoDevelop 5.5 with Mono 3.2.8.

**Comment by coder2000** [comment]
Mono isn't a supported environment at this time.
